# Generated by Django 4.2.11 on 2024-04-27 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_location",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "drop_off_location",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "current_location",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STATUS_AVAILABLE", "Available"),
                            ("STATUS_NOT_AVAILABLE", "Not available"),
                            ("STATUS_REQUESTED", "Requested"),
                            ("STATUS_STARTED", "Started"),
                            ("STATUS_COMPLETED", "Completed"),
                            ("STATUS_CANCELLED", "Cancelled"),
                        ],
                        default="STATUS_AVAILABLE",
                        max_length=30,
                    ),
                ),
                (
                    "status_details",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
